# Generated by Django 4.0.4 on 2022-09-17 12:10

import Account.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profession_Name', models.CharField(max_length=100)),
                ('Profession_Outside_Image', models.FileField(upload_to='Profession_Outside_Image', validators=[Account.validator.Image_file_size])),
                ('Profession_Inside_Image', models.FileField(upload_to='Profession_Inside_Image', validators=[Account.validator.Image_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_image', models.FileField(upload_to='Profession', validators=[Account.validator.Image_file_size])),
                ('year_of_experience', models.IntegerField(blank=True, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_start_time', models.TimeField(blank=True, null=True)),
                ('shop_close_time', models.TimeField(blank=True, null=True)),
                ('shop_address', models.TextField(blank=True, null=True)),
                ('shop_city', models.CharField(max_length=50)),
                ('shop_state', models.CharField(max_length=50)),
                ('shop_status_sunday', models.BooleanField(blank=True, null=True)),
                ('shop_status_monday', models.BooleanField(blank=True, null=True)),
                ('shop_status_Tuesday', models.BooleanField(blank=True, null=True)),
                ('shop_status_Wednesday', models.BooleanField(blank=True, null=True)),
                ('shop_status_Thrusday', models.BooleanField(blank=True, null=True)),
                ('shop_status_Friday', models.BooleanField(blank=True, null=True)),
                ('shop_status_saturday', models.BooleanField(blank=True, null=True)),
                ('shop_description', models.TextField(blank=True, null=True)),
                ('shop_Longititude', models.TextField(blank=True, null=True)),
                ('shop_Latitude', models.TextField(blank=True, null=True)),
                ('Profession_Rating', models.FloatField(default=0)),
                ('profession_longitude', models.FloatField(blank=True, null=True)),
                ('profession_latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.FileField(blank=True, default='default.webp', null=True, upload_to='Profile_Pic', validators=[Account.validator.Image_file_size])),
                ('terms_conditions', models.BooleanField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=10, null=True)),
                ('usertype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Recent_serach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profession_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.profession')),
                ('User_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Professionvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Video/%y', validators=[Account.validator.video_file_size])),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.profession')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.CharField(max_length=10)),
                ('Profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Professionimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Profession', validators=[Account.validator.Image_file_size])),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.profession')),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='UserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile'),
        ),
        migrations.AddField(
            model_name='profession',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.admin_profession'),
        ),
        migrations.CreateModel(
            name='nearest_profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('near', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.state')),
            ],
        ),
    ]
