# Generated by Django 3.2.11 on 2022-09-12 11:17

import Account.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_profession',
            name='Profession_Inside_Image',
            field=models.FileField(upload_to='Profession_Inside_Image', validators=[Account.validator.Image_file_size]),
        ),
        migrations.AlterField(
            model_name='admin_profession',
            name='Profession_Outside_Image',
            field=models.FileField(upload_to='Profession_Outside_Image', validators=[Account.validator.Image_file_size]),
        ),
        migrations.AlterField(
            model_name='profession',
            name='profession_image',
            field=models.FileField(upload_to='Profession', validators=[Account.validator.Image_file_size]),
        ),
        migrations.AlterField(
            model_name='professionimage',
            name='image',
            field=models.FileField(upload_to='Profession', validators=[Account.validator.Image_file_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='Profile_Pic', validators=[Account.validator.Image_file_size]),
        ),
    ]
