# Generated by Django 4.0.4 on 2022-09-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_professionreview_review_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionreview_reply',
            name='Review',
        ),
        migrations.RemoveField(
            model_name='professionreview_reply',
            name='User_Profile',
        ),
        migrations.DeleteModel(
            name='ProfessionReview',
        ),
        migrations.DeleteModel(
            name='ProfessionReview_Reply',
        ),
    ]
