# Generated by Django 4.0.4 on 2022-09-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_professionreview_reply_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='shop_Latitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='shop_Longititude',
            field=models.TextField(blank=True, null=True),
        ),
    ]
