# Generated by Django 4.1 on 2022-09-07 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0003_remove_professionreview_reply_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='profession_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='profession_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='nearest_profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('near', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
