# Generated by Django 4.0.4 on 2022-09-17 11:29

import Account.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_userprofile_city_alter_userprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, default='default.webp', null=True, upload_to='Profile_Pic', validators=[Account.validator.Image_file_size]),
        ),
    ]
