# Generated by Django 4.0.4 on 2022-09-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_profession_profession_latitude_and_more'),
        ('Account', '0004_profession_shop_latitude_profession_shop_longititude'),
    ]

    operations = [
    ]
