# Generated by Django 4.0.4 on 2022-09-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_merge_20220909_1023'),
        ('Account', '0005_merge_20220909_1025'),
    ]

    operations = [
    ]
