# Generated by Django 4.0.4 on 2022-09-05 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_like',
            name='profession',
        ),
        migrations.AddField(
            model_name='review_like',
            name='Profession_Review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professional.professionreview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professionreview',
            name='Review_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 5, 15, 9, 59, 843502)),
        ),
        migrations.AlterField(
            model_name='professionreview_reply',
            name='Review_Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 5, 15, 9, 59, 843502)),
        ),
    ]
