# Generated by Django 4.0.4 on 2022-09-06 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_remove_review_like_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionreview',
            name='Reply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionreview',
            name='Review_Date',
            field=models.DateField(default=datetime.date(2022, 9, 6)),
        ),
        migrations.AlterField(
            model_name='professionreview',
            name='Review_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 24, 28, 410314)),
        ),
        migrations.AlterField(
            model_name='professionreview_reply',
            name='Review_Reply_Date',
            field=models.DateField(default=datetime.date(2022, 9, 6)),
        ),
        migrations.AlterField(
            model_name='professionreview_reply',
            name='Review_Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 24, 28, 410314)),
        ),
    ]
