# Generated by Django 4.1 on 2022-09-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_alter_professionreview_review_time_and_more'),
        ('professional', '0006_alter_professionreview_review_time_and_more'),
    ]

    operations = [
    ]
