# Generated by Django 4.0.4 on 2022-09-15 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0006_alter_professionreview_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionreview',
            name='Review_Date',
            field=models.DateField(default=datetime.date(2022, 9, 15)),
        ),
        migrations.AlterField(
            model_name='professionreview',
            name='Review_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 15, 16, 25, 14, 983195)),
        ),
        migrations.AlterField(
            model_name='professionreview_reply',
            name='Review_Reply_Date',
            field=models.DateField(default=datetime.date(2022, 9, 15)),
        ),
        migrations.AlterField(
            model_name='professionreview_reply',
            name='Review_Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 15, 16, 25, 14, 999376)),
        ),
    ]
