# Generated by Django 4.0.2 on 2022-09-26 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('professional', '0008_alter_professionreview_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionreview',
            name='Review_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 26, 17, 47, 2, 495669)),
        ),
        migrations.AlterField(
            model_name='professionreview',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to='Account.UserProfile'),
        ),
        migrations.AlterField(
            model_name='professionreview_reply',
            name='Review_Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 26, 17, 47, 2, 496668)),
        ),
    ]
