# Generated by Django 4.0.4 on 2022-10-31 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0013_alter_professionreview_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionreview',
            name='Review_Time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 31, 16, 18, 28, 457558)),
        ),
        migrations.AlterField(
            model_name='professionreview_reply',
            name='Review_Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 31, 16, 18, 28, 459579)),
        ),
        migrations.DeleteModel(
            name='Review_Like',
        ),
    ]
