# Generated by Django 4.0.4 on 2022-09-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0016_alter_professionreview_review_date_and_more'),
        ('professional', '0016_alter_professionreview_review_time_and_more'),
    ]

    operations = [
    ]
