# Generated by Django 4.0.4 on 2022-09-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0017_merge_20220908_1135'),
        ('professional', '0018_alter_professionreview_review_time_and_more'),
    ]

    operations = [
    ]
