# Generated by Django 4.0.4 on 2022-09-19 10:38

import Account.validator
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Community_Name', models.CharField(max_length=70)),
                ('Community_Cover_Image', models.ImageField(blank=True, null=True, upload_to='Community_Cover_image')),
                ('Community_Profile_Image', models.ImageField(upload_to='Community_Profile_Image')),
                ('Public', models.BooleanField(default=False)),
                ('Private', models.BooleanField(default=False)),
                ('Restricted', models.BooleanField(default=False)),
                ('Adult_Content', models.BooleanField(default=False)),
                ('Community_Type', models.BooleanField(default=True)),
                ('community_member', models.IntegerField(blank=True, default=0, null=True)),
                ('community_Description', models.TextField(blank=True, null=True)),
                ('User_Profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Community_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Community_type', models.CharField(blank=True, max_length=50, null=True)),
                ('Community_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.community')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='Image', validators=[Account.validator.Image_file_size])),
                ('Video', models.FileField(blank=True, null=True, upload_to='Video', validators=[Account.validator.video_file_size])),
                ('Description', models.TextField()),
                ('Date', models.DateField(default=datetime.date(2022, 9, 19))),
                ('Time', models.TimeField(default=datetime.datetime(2022, 9, 19, 16, 8, 46, 722673))),
                ('comment', models.IntegerField(blank=True, null=True)),
                ('News_bookmark', models.BooleanField(default=False)),
                ('News_like', models.ManyToManyField(blank=True, null=True, related_name='News_like', to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='News_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('reply', models.IntegerField(blank=True, default=0, null=True)),
                ('News_comment_like', models.ManyToManyField(blank=True, null=True, related_name='News_comment_like', to='Account.userprofile')),
                ('News_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.news')),
                ('User_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='Post', validators=[Account.validator.Image_file_size])),
                ('Description', models.TextField(blank=True, null=True)),
                ('Post_Date', models.DateField(blank=True, null=True)),
                ('Post_Time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Post_comment', models.IntegerField(blank=True, null=True)),
                ('post_type1', models.BooleanField(blank=True, null=True)),
                ('Post_bookmark', models.BooleanField(default=False)),
                ('Like', models.ManyToManyField(blank=True, null=True, related_name='liked', to='Account.userprofile')),
                ('User_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Profile', to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='User_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('User_id', models.TextField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('answer', models.IntegerField(blank=True, null=True)),
                ('Answer_later', models.BooleanField(default=False)),
                ('Question_Edit', models.BooleanField(blank=True, default=False, null=True)),
                ('Question_bookmark', models.BooleanField(default=False)),
                ('Question_Like', models.ManyToManyField(blank=True, null=True, related_name='Question_Like', to='Account.userprofile')),
                ('User_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='User_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField()),
                ('reply', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('Answer_Like', models.ManyToManyField(blank=True, null=True, related_name='Answer_Like', to='Account.userprofile')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.user_question')),
                ('User_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('report_time', models.TimeField(blank=True, null=True)),
                ('adult_content', models.BooleanField(default=False)),
                ('abusing_content', models.BooleanField(default=False)),
                ('report_description', models.TextField()),
                ('community_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_profession.community')),
                ('news_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_profession.news')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_profession.userpost')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_profession.user_question')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.user_question')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Commment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(blank=True, null=True)),
                ('Comment_Date', models.DateField(blank=True, null=True)),
                ('Commenet_Time', models.TimeField(blank=True, null=True)),
                ('Post_comment_reply', models.IntegerField(blank=True, null=True)),
                ('Comment_like', models.ManyToManyField(blank=True, null=True, related_name='Comment_like', to='Account.userprofile')),
                ('User_Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.userpost')),
                ('User_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Comment_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('Post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.post_commment')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='POST_and_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_profession.userpost')),
                ('Question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_profession.user_question')),
            ],
        ),
        migrations.CreateModel(
            name='News_Main_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.news')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='News_Comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reply', models.TextField()),
                ('Reply_Date', models.DateField(default=datetime.date.today)),
                ('Reply_Time', models.TimeField(default=datetime.datetime(2022, 9, 19, 16, 8, 46, 738298))),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.news_comment')),
                ('User_Profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='News_Comment_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('news_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.news_comment')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.userpost')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Join_Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commnunity_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_profession.community')),
                ('User_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='distance_calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.JSONField()),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Community_Post_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Community_Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.post_commment')),
                ('Community_Post_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.community_post')),
            ],
        ),
        migrations.AddField(
            model_name='community_post',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.userpost'),
        ),
        migrations.CreateModel(
            name='Community_Comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reply', models.TextField()),
                ('Reply_Date', models.DateField(blank=True, null=True)),
                ('Reply_Time', models.TimeField(blank=True, null=True)),
                ('Community_Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.community_post_comment')),
                ('User_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reply', models.TextField()),
                ('Reply_Date', models.DateField(blank=True, null=True)),
                ('Reply_Time', models.TimeField(blank=True, null=True)),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.post_commment')),
                ('User_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_profession.news')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_profession.userpost')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_profession.user_question')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reply', models.TextField()),
                ('Reply_date', models.DateField(blank=True, null=True)),
                ('Reply_Time', models.TimeField(blank=True, null=True)),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.user_answer')),
                ('User_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.user_answer')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_later',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.user_question')),
                ('User_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
    ]
