# Generated by Django 4.0.4 on 2022-09-03 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_later',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 3, 13, 37, 3, 228816)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 3, 13, 37, 3, 228816)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 3, 13, 37, 3, 228816)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 3, 13, 37, 3, 228816)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 3, 13, 37, 3, 228816)),
        ),
    ]
