# Generated by Django 3.2.11 on 2022-09-11 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 11, 15, 47, 23, 327176)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 11, 15, 47, 23, 337751)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Question_Edit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
