# Generated by Django 4.0.4 on 2022-09-19 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0002_alter_news_time_alter_news_comment_reply_reply_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 19, 17, 4, 57, 643717)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 19, 17, 4, 57, 643717)),
        ),
    ]
