# Generated by Django 4.0.4 on 2022-09-17 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0003_alter_news_time_alter_news_comment_reply_reply_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='abusing_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='adult_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 17, 18, 13, 42, 829992)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 17, 18, 13, 42, 829992)),
        ),
    ]
