# Generated by Django 3.2.11 on 2022-09-12 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0003_alter_news_time_alter_news_comment_reply_reply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 12)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 12, 14, 1, 10, 508043)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 12, 14, 1, 10, 508043)),
        ),
    ]
