# Generated by Django 4.0.4 on 2022-11-14 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0003_alter_news_time_alter_news_comment_reply_reply_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 11, 14)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 14, 11, 11, 4, 157324)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 14, 11, 11, 4, 157324)),
        ),
    ]
