# Generated by Django 3.2.11 on 2022-09-12 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0004_auto_20220912_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 12, 16, 47, 18, 731303)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 12, 16, 47, 18, 731303)),
        ),
    ]
