# Generated by Django 4.0.4 on 2022-09-17 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0004_report_abusing_content_report_adult_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 17, 18, 32, 24, 730560)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 17, 18, 32, 24, 746181)),
        ),
    ]
