# Generated by Django 4.0.4 on 2022-09-06 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_professionreview_reply_review_and_more'),
        ('community_profession', '0005_alter_answer_later_time_alter_news_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_question',
            name='Question_Like',
            field=models.ManyToManyField(blank=True, null=True, related_name='Question_Like', to='Account.userprofile'),
        ),
        migrations.AlterField(
            model_name='answer_later',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 6)),
        ),
        migrations.AlterField(
            model_name='answer_later',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 13, 59, 52, 79)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 6)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 13, 59, 52, 79)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 6)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 13, 59, 52, 79)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 13, 59, 52, 79)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 6)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 13, 59, 52, 79)),
        ),
        migrations.CreateModel(
            name='Question_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.userpost')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
    ]
