# Generated by Django 4.0.4 on 2022-09-14 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0005_auto_20220912_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_reply',
            name='Reply_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer_reply',
            name='Reply_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 14)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 14, 12, 58, 16, 36815)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 14, 12, 58, 16, 36815)),
        ),
    ]
