# Generated by Django 4.0.4 on 2022-09-14 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0006_answer_reply_reply_time_answer_reply_reply_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 14, 16, 56, 8, 360923)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 14, 16, 56, 8, 363921)),
        ),
    ]
