# Generated by Django 4.0.4 on 2022-09-06 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0006_user_question_question_like_alter_answer_later_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_later',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 14, 5, 36, 462998)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 14, 5, 36, 462998)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 14, 5, 36, 462998)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 14, 5, 36, 462998)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 14, 5, 36, 462998)),
        ),
    ]
