# Generated by Django 4.0.4 on 2022-09-06 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0007_alter_answer_later_time_alter_news_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_later',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 1, 49, 156050)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 1, 49, 156050)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 1, 49, 156050)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 1, 49, 156050)),
        ),
        migrations.AlterField(
            model_name='question_like',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.user_question'),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 1, 49, 140396)),
        ),
    ]
