# Generated by Django 4.0.4 on 2022-09-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0007_alter_news_time_alter_news_comment_reply_reply_time'),
        ('community_profession', '0007_news_news_bookmark_user_question_question_bookmark_and_more'),
    ]

    operations = [
    ]
