# Generated by Django 4.0.4 on 2022-09-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0006_alter_answer_later_time_alter_news_time_and_more'),
        ('community_profession', '0008_alter_answer_later_time_alter_news_time_and_more'),
    ]

    operations = [
    ]
