# Generated by Django 4.0.4 on 2022-09-15 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0008_merge_20220915_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 15, 16, 50, 24, 586478)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 15, 16, 50, 24, 589477)),
        ),
    ]
