# Generated by Django 4.0.4 on 2022-09-06 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0009_merge_20220906_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_later',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 24, 28, 402207)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 24, 28, 402207)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 24, 28, 402207)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 24, 28, 402207)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 15, 24, 28, 394213)),
        ),
    ]
