# Generated by Django 4.0.4 on 2022-09-07 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0009_merge_20220906_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_later',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 7)),
        ),
        migrations.AlterField(
            model_name='answer_later',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 10, 20, 20, 903253)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 7)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 10, 20, 20, 903253)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 7)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 10, 20, 20, 903253)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 10, 20, 20, 903253)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 7)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 10, 20, 20, 887662)),
        ),
    ]
