# Generated by Django 4.1 on 2022-09-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0009_merge_20220906_1552'),
        ('community_profession', '0009_merge_20220906_1659'),
        ('community_profession', '0010_alter_answer_later_time_alter_news_time_and_more'),
    ]

    operations = [
    ]
