# Generated by Django 4.1 on 2022-09-07 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0011_merge_20220907_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_later',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 7)),
        ),
        migrations.AlterField(
            model_name='answer_later',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 11, 2, 29, 277451)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 7)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 11, 2, 29, 277451)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 7)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 11, 2, 29, 277451)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 11, 2, 29, 277451)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 7)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 11, 2, 29, 275157)),
        ),
    ]
