# Generated by Django 4.0.4 on 2022-09-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0010_alter_answer_later_date_alter_answer_later_time_and_more'),
        ('community_profession', '0011_merge_20220907_0745'),
    ]

    operations = [
    ]
