# Generated by Django 4.0.4 on 2022-09-07 06:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_profession_shop_latitude_profession_shop_longititude'),
        ('community_profession', '0012_merge_20220907_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_commment',
            name='Post_comment_reply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer_later',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 11, 54, 50, 636686)),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 11, 54, 50, 636686)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 11, 54, 50, 636686)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 11, 54, 50, 636686)),
        ),
        migrations.RemoveField(
            model_name='post_commment',
            name='Comment_like',
        ),
        migrations.AddField(
            model_name='post_commment',
            name='Comment_like',
            field=models.ManyToManyField(blank=True, null=True, related_name='Comment_like', to='Account.userprofile'),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 11, 54, 50, 628692)),
        ),
        migrations.CreateModel(
            name='Post_Comment_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('Post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.post_commment')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
    ]
