# Generated by Django 4.0.4 on 2022-10-31 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0013_alter_news_date_alter_news_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='news_comment_like',
            name='news_comment',
        ),
        migrations.RemoveField(
            model_name='news_comment_like',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='news_main_like',
            name='news',
        ),
        migrations.RemoveField(
            model_name='news_main_like',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='post_comment_like',
            name='Post_comment',
        ),
        migrations.RemoveField(
            model_name='post_comment_like',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='question_like',
            name='Question',
        ),
        migrations.RemoveField(
            model_name='question_like',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 31, 16, 18, 28, 432789)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 31, 16, 18, 28, 434784)),
        ),
        migrations.DeleteModel(
            name='Answer_Like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='News_Comment_Like',
        ),
        migrations.DeleteModel(
            name='News_Main_Like',
        ),
        migrations.DeleteModel(
            name='Post_Comment_Like',
        ),
        migrations.DeleteModel(
            name='Question_Like',
        ),
    ]
