# Generated by Django 4.0.4 on 2022-09-07 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0013_post_commment_post_comment_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_later',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer_later',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 15, 41, 49, 280527)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 15, 41, 49, 280527)),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
