# Generated by Django 4.0.4 on 2022-09-07 10:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_profession_shop_latitude_profession_shop_longititude'),
        ('community_profession', '0014_alter_answer_later_date_alter_answer_later_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='Answer_Like',
            field=models.ManyToManyField(blank=True, null=True, related_name='Answer_Like', to='Account.userprofile'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 15, 56, 38, 523105)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 15, 56, 38, 538714)),
        ),
        migrations.CreateModel(
            name='Answer_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_profession.user_answer')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
    ]
