# Generated by Django 4.0.4 on 2022-09-07 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0015_user_answer_answer_like_alter_news_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='reply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 16, 1, 14, 280906)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 16, 1, 14, 280906)),
        ),
    ]
