# Generated by Django 4.0.4 on 2022-09-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0012_merge_20220907_1036'),
        ('community_profession', '0017_user_answer_date_user_answer_time_alter_news_time_and_more'),
    ]

    operations = [
    ]
