# Generated by Django 4.0.4 on 2022-09-07 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_profession_shop_latitude_profession_shop_longititude'),
        ('community_profession', '0018_merge_20220907_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='News_like',
            field=models.ManyToManyField(blank=True, null=True, related_name='News_like', to='Account.userprofile'),
        ),
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='news_comment',
            name='News_comment_like',
            field=models.ManyToManyField(blank=True, null=True, related_name='News_comment_like', to='Account.userprofile'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 17, 33, 1, 262308)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 17, 33, 1, 270421)),
        ),
    ]
