# Generated by Django 4.0.4 on 2022-09-07 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0020_alter_news_time_alter_news_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_comment',
            name='comment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 18, 18, 10, 796914)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 18, 18, 10, 796914)),
        ),
    ]
