# Generated by Django 4.0.4 on 2022-09-07 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0021_news_comment_comment_alter_news_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_comment',
            old_name='comment',
            new_name='Reply',
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 18, 18, 35, 549179)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 18, 18, 35, 549179)),
        ),
    ]
