# Generated by Django 4.0.4 on 2022-09-07 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0022_rename_comment_news_comment_reply_alter_news_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_comment',
            name='Reply',
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 18, 20, 44, 894645)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 18, 20, 44, 894645)),
        ),
    ]
