# Generated by Django 4.0.4 on 2022-09-07 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0023_remove_news_comment_reply_alter_news_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_comment',
            name='reply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 18, 24, 14, 514149)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 18, 24, 14, 518154)),
        ),
    ]
