# Generated by Django 4.0.4 on 2022-09-07 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0027_alter_news_time_alter_news_comment_reply_reply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_comment',
            name='reply',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 18, 36, 20, 48415)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 7, 18, 36, 20, 48415)),
        ),
    ]
