# Generated by Django 4.0.4 on 2022-09-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0018_merge_20220907_1700'),
        ('community_profession', '0028_news_comment_reply_alter_news_time_and_more'),
    ]

    operations = [
    ]
