# Generated by Django 4.0.4 on 2022-09-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0030_alter_news_date_alter_news_time_and_more'),
        ('community_profession', '0030_alter_news_time_alter_news_comment_reply_reply_time'),
    ]

    operations = [
    ]
