# Generated by Django 4.0.4 on 2022-09-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0031_merge_20220908_1135'),
        ('community_profession', '0032_alter_news_time_alter_news_comment_reply_reply_time'),
    ]

    operations = [
    ]
