# Generated by Django 4.0.4 on 2022-09-08 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_profession_shop_latitude_profession_shop_longititude'),
        ('community_profession', '0034_alter_news_time_alter_news_comment_reply_reply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_member',
            field=models.ManyToManyField(blank=True, null=True, related_name='community_member', to='Account.userprofile'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 8, 14, 55, 58, 596678)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 8, 14, 55, 58, 596678)),
        ),
    ]
