# Generated by Django 4.0.4 on 2022-09-08 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0035_community_community_member_alter_news_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='community_member',
        ),
        migrations.AddField(
            model_name='community',
            name='community_member',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 8, 15, 7, 19, 42265)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 8, 15, 7, 19, 42265)),
        ),
    ]
