# Generated by Django 4.0.4 on 2022-09-08 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0036_remove_community_community_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_member',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 8, 15, 18, 55, 247959)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 8, 15, 18, 55, 247959)),
        ),
    ]
