# Generated by Django 4.1 on 2022-09-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0013_alter_answer_later_time_alter_news_time_and_more'),
        ('community_profession', '0039_alter_news_time_alter_news_comment_reply_reply_time'),
    ]

    operations = [
    ]
