# Generated by Django 4.0.4 on 2022-09-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0040_merge_20220909_1023'),
        ('community_profession', '0041_alter_answer_later_date_alter_answer_later_time_and_more'),
    ]

    operations = [
    ]
