# Generated by Django 4.0.4 on 2022-09-09 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0043_alter_news_time_alter_news_comment_reply_reply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_later',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 9, 15, 18, 54, 466577)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 9, 15, 18, 54, 482174)),
        ),
    ]
