# Generated by Django 4.1 on 2022-09-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0044_alter_news_time_alter_news_comment_reply_reply_time'),
        ('community_profession', '0045_remove_answer_later_active_and_more'),
    ]

    operations = [
    ]
