# Generated by Django 4.0.4 on 2022-09-09 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0046_merge_20220909_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 9, 15, 48, 35, 933723)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 9, 15, 48, 35, 938674)),
        ),
    ]
