# Generated by Django 4.0.4 on 2022-09-09 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0046_merge_20220909_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_question',
            name='Question_Edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 9, 15, 34, 42, 130559)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 9, 15, 34, 42, 130559)),
        ),
    ]
