# Generated by Django 4.1 on 2022-09-09 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_merge_20220909_1115'),
        ('community_profession', '0047_alter_news_time_alter_news_comment_reply_reply_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 9, 23, 27, 25, 718221)),
        ),
        migrations.AlterField(
            model_name='news_comment_reply',
            name='Reply_Time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 9, 23, 27, 25, 718221)),
        ),
        migrations.CreateModel(
            name='distance_calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.JSONField()),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
    ]
