# Generated by Django 4.0.4 on 2022-09-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_profession', '0047_alter_news_time_alter_news_comment_reply_reply_time'),
        ('community_profession', '0047_user_question_question_edit_alter_news_time_and_more'),
    ]

    operations = [
    ]
